language: python

python:
  - 2.7
  - 3.4

before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-3.5.5-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.5.5-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/mc
  - export PATH=/home/travis/mc/bin:$PATH

install:
  - conda update conda --yes
  - conda create -n testenv --yes pip python=$TRAVIS_PYTHON_VERSION
  - conda update conda --yes
  - conda install conda-build jinja2 --yes
  - source activate testenv
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then conda install --yes imaging; else pip install pillow; fi
  - conda install --yes numpy scipy nose six
  - git clone -b xraylib --single-branch --depth=1 https://github.com/tacaswell/conda-recipes.git ../conda-recipes
  - conda build ../conda-recipes/xraylib
  - conda install xraylib --use-local --yes
  - conda install scikit-image --yes
  - pip install coveralls
  - python setup.py install

script:
  - python run_tests.py

after_success:
  coveralls
